#!/usr/bin/env python3
"""Generate provider defaults, enums, config structs, env registry, and keyring from providers.toml."""

from __future__ import annotations

import pathlib
import tomllib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "crates" / "shared-defs" / "providers.toml"

OUT_DEFAULTS_CONFIG = ROOT / "crates" / "config" / "src" / "generated" / "provider_defaults.rs"
OUT_KIND = ROOT / "crates" / "config" / "src" / "generated" / "provider_kind.rs"
OUT_PROVIDERS_TOML = ROOT / "crates" / "config" / "src" / "generated" / "providers_toml.rs"
OUT_ENV_CONFIG = ROOT / "crates" / "config" / "src" / "generated" / "provider_env.rs"

OUT_DEFAULTS_RUNTIME = (
    ROOT / "crates" / "runtime-server" / "src" / "config" / "generated" / "provider_defaults.rs"
)
OUT_API = ROOT / "crates" / "runtime-server" / "src" / "config" / "generated" / "api_provider.rs"
OUT_PROVIDERS_CFG = (
    ROOT / "crates" / "runtime-server" / "src" / "config" / "generated" / "providers_config.rs"
)
OUT_ENV_RUNTIME = (
    ROOT / "crates" / "runtime-server" / "src" / "config" / "generated" / "provider_env.rs"
)

OUT_KEYRING = ROOT / "crates" / "secrets" / "src" / "generated" / "keyring_slots.rs"
OUT_EXAMPLE = ROOT / "crates" / "shared-defs" / "generated" / "providers.example.toml.fragment"
OUT_DRIFT = ROOT / "crates" / "shared-defs" / "generated" / "provider_ids.txt"

HEADER = [
    "// @generated by scripts/generate-providers.py — do not edit.",
    "// Source: crates/shared-defs/providers.toml",
    "",
]


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def rust_str_slice(items: list[str]) -> str:
    if not items:
        return "&[]"
    return "&[" + ", ".join(rust_str(x) for x in items) + "]"


def const_name(prefix: str, toml_field: str, suffix: str) -> str:
    return f"{prefix}_{toml_field.upper()}_{suffix}"


def parse_patterns(p: dict, *, runtime: bool) -> list[str]:
    pats = [p["id"], *(p.get("aliases") or [])]
    if runtime:
        pats.extend(p.get("runtime_extra_aliases") or [])
    seen: set[str] = set()
    out: list[str] = []
    for x in pats:
        if x not in seen:
            seen.add(x)
            out.append(x)
    return out


def gen_defaults(providers: list[dict]) -> str:
    lines = list(HEADER)
    for p in providers:
        field = p["toml_field"]
        model_c = const_name("DEFAULT", field, "MODEL")
        base_c = const_name("DEFAULT", field, "BASE_URL")
        lines.append(f"pub const {model_c}: &str = {rust_str(p['default_model'])};")
        lines.append(f"pub const {base_c}: &str = {rust_str(p['default_base_url'])};")
        flash = p.get("default_flash_model")
        if flash:
            flash_c = const_name("DEFAULT", field, "FLASH_MODEL")
            lines.append(f"pub const {flash_c}: &str = {rust_str(flash)};")
        lines.append("")
    return "\n".join(lines)


def gen_provider_kind(facade: list[dict]) -> str:
    lines = list(HEADER)
    lines.extend(
        [
            "use serde::{Deserialize, Serialize};",
            "",
            "#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]",
            '#[serde(rename_all = "kebab-case")]',
            "pub enum ProviderKind {",
        ]
    )
    for i, p in enumerate(facade):
        if i == 0:
            lines.append("    #[default]")
        rename = p.get("serde_rename")
        if rename:
            lines.append(f"    #[serde(rename = {rust_str(rename)})]")
        lines.append(f"    {p['rust_variant']},")
    lines.extend(
        [
            "    /// User-defined OpenAI-compatible provider (see `[custom_providers]`).",
            "    Custom,",
            "}",
            "",
            "impl ProviderKind {",
            "    /// All facade provider kinds. Kept in sync with the runtime's",
            "    /// `ApiProvider` enum by the kernel-v2 M0.5 drift tests",
            "    /// (`crates/runtime-server/src/config/providers.rs`).",
            "    pub const ALL: &'static [Self] = &[",
        ]
    )
    for p in facade:
        lines.append(f"        Self::{p['rust_variant']},")
    lines.extend(
        [
            "        Self::Custom,",
            "    ];",
            "",
            "    #[must_use]",
            "    pub fn as_str(self) -> &'static str {",
            "        match self {",
        ]
    )
    for p in facade:
        lines.append(f"            Self::{p['rust_variant']} => {rust_str(p['id'])},")
    lines.extend(
        [
            '            Self::Custom => "custom",',
            "        }",
            "    }",
            "",
            "    /// Canonical keyring slot for this provider (Custom uses dynamic `custom-{id}`).",
            "    #[must_use]",
            "    pub fn keyring_slot(self) -> &'static str {",
            "        match self {",
        ]
    )
    for p in facade:
        lines.append(
            f"            Self::{p['rust_variant']} => {rust_str(p['keyring_slot'])},"
        )
    lines.extend(
        [
            '            Self::Custom => "custom",',
            "        }",
            "    }",
            "",
            "    #[must_use]",
            "    pub fn is_custom(self) -> bool {",
            "        matches!(self, Self::Custom)",
            "    }",
            "",
            "    #[must_use]",
            "    pub fn parse(value: &str) -> Option<Self> {",
            "        match value.trim().to_ascii_lowercase().as_str() {",
            '            "custom" => Some(Self::Custom),',
        ]
    )
    for p in facade:
        pats = " | ".join(rust_str(x) for x in parse_patterns(p, runtime=False))
        lines.append(f"            {pats} => Some(Self::{p['rust_variant']}),")
    lines.extend(
        [
            "            _ => None,",
            "        }",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def gen_api_provider(providers: list[dict]) -> str:
    lines = list(HEADER)
    lines.extend(
        [
            "use serde::{Deserialize, Serialize};",
            "",
            "#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]",
            '#[serde(rename_all = "snake_case")]',
            "pub enum ApiProvider {",
        ]
    )
    for p in providers:
        lines.append(f"    {p['rust_variant']},")
    lines.extend(
        [
            "}",
            "",
            "impl ApiProvider {",
            "    #[must_use]",
            "    pub fn parse(value: &str) -> Option<Self> {",
            "        match value.trim().to_ascii_lowercase().as_str() {",
        ]
    )
    for p in providers:
        pats = parse_patterns(p, runtime=True)
        joined = " | ".join(rust_str(x) for x in pats)
        # Keep rustfmt happy on long alias lists (e.g. deepseek-cn).
        if len(joined) > 70:
            lines.append(f"            {joined} => {{")
            lines.append(f"                Some(Self::{p['rust_variant']})")
            lines.append("            }")
        else:
            lines.append(f"            {joined} => Some(Self::{p['rust_variant']}),")
    lines.extend(
        [
            "            _ => None,",
            "        }",
            "    }",
            "",
            "    #[must_use]",
            "    pub fn as_str(self) -> &'static str {",
            "        match self {",
        ]
    )
    for p in providers:
        lines.append(f"            Self::{p['rust_variant']} => {rust_str(p['id'])},")
    lines.extend(
        [
            "        }",
            "    }",
            "",
            "    /// Canonical keyring / env slot (DeepseekCN shares `deepseek`).",
            "    #[must_use]",
            "    pub fn keyring_slot(self) -> &'static str {",
            "        match self {",
        ]
    )
    for p in providers:
        lines.append(
            f"            Self::{p['rust_variant']} => {rust_str(p['keyring_slot'])},"
        )
    lines.extend(
        [
            "        }",
            "    }",
            "",
            "    /// Human-friendly label for picker UIs / status chips.",
            "    #[must_use]",
            "    pub fn display_name(self) -> &'static str {",
            "        match self {",
        ]
    )
    for p in providers:
        name = p.get("display_name", p["id"])
        lines.append(f"            Self::{p['rust_variant']} => {rust_str(name)},")
    lines.extend(
        [
            "        }",
            "    }",
            "",
            "    /// All providers, in the order shown in the picker.",
            "    #[must_use]",
            "    pub fn all() -> &'static [Self] {",
            "        &[",
        ]
    )
    for p in providers:
        lines.append(f"            Self::{p['rust_variant']},")
    lines.extend(
        [
            "        ]",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def gen_providers_toml(facade: list[dict]) -> str:
    lines = list(HEADER)
    lines.extend(
        [
            "use serde::{Deserialize, Serialize};",
            "",
            "use super::provider_kind::ProviderKind;",
            "use crate::ProviderConfigToml;",
            "",
            "#[derive(Debug, Clone, Serialize, Deserialize, Default)]",
            "pub struct ProvidersToml {",
        ]
    )
    for p in facade:
        lines.append("    #[serde(default)]")
        lines.append(f"    pub {p['toml_field']}: ProviderConfigToml,")
    lines.extend(
        [
            "}",
            "",
            "impl ProvidersToml {",
            "    #[must_use]",
            "    pub fn for_provider(&self, provider: ProviderKind) -> &ProviderConfigToml {",
            "        match provider {",
        ]
    )
    for p in facade:
        lines.append(f"            ProviderKind::{p['rust_variant']} => &self.{p['toml_field']},")
    openai_field = next(p["toml_field"] for p in facade if p["id"] == "openai")
    lines.extend(
        [
            "            // Custom entries live in `ConfigToml.custom_providers`, not `[providers.*]`.",
            f"            ProviderKind::Custom => &self.{openai_field},",
            "        }",
            "    }",
            "",
            "    pub fn for_provider_mut(&mut self, provider: ProviderKind) -> &mut ProviderConfigToml {",
            "        match provider {",
        ]
    )
    for p in facade:
        lines.append(
            f"            ProviderKind::{p['rust_variant']} => &mut self.{p['toml_field']},"
        )
    lines.extend(
        [
            f"            ProviderKind::Custom => &mut self.{openai_field},",
            "        }",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def gen_providers_config(providers: list[dict]) -> str:
    lines = [
        "// @generated by scripts/generate-providers.py — do not edit.",
        "// Source: crates/shared-defs/providers.toml",
        "// Included from crates/runtime-server/src/config/types.rs",
        "",
        "#[derive(Debug, Clone, Default, Deserialize)]",
        "pub struct ProvidersConfig {",
    ]
    for p in providers:
        lines.append("    #[serde(default)]")
        lines.append(f"    pub {p['toml_field']}: ProviderConfig,")
    lines.extend(["}", ""])
    return "\n".join(lines)


def gen_provider_env(providers: list[dict]) -> str:
    lines = list(HEADER)
    lines.extend(
        [
            "/// Env override metadata for a chat provider (from providers.toml).",
            "#[derive(Debug, Clone, Copy)]",
            "pub struct ProviderEnvDef {",
            "    pub id: &'static str,",
            "    pub toml_field: &'static str,",
            "    pub env_base_url: &'static [&'static str],",
            "    pub env_model: &'static [&'static str],",
            "    /// When true, `env_base_url` writes root `base_url` (DeepSeek legacy).",
            "    pub base_url_writes_root: bool,",
            "    /// When true, `env_model` applies regardless of active provider.",
            "    pub model_env_global: bool,",
            "    pub runtime_only: bool,",
            "}",
            "",
            "pub static PROVIDER_ENV_REGISTRY: &[ProviderEnvDef] = &[",
        ]
    )
    for p in providers:
        lines.append("    ProviderEnvDef {")
        lines.append(f"        id: {rust_str(p['id'])},")
        lines.append(f"        toml_field: {rust_str(p['toml_field'])},")
        lines.append(f"        env_base_url: {rust_str_slice(p.get('env_base_url') or [])},")
        lines.append(f"        env_model: {rust_str_slice(p.get('env_model') or [])},")
        lines.append(
            f"        base_url_writes_root: {'true' if p.get('base_url_writes_root') else 'false'},"
        )
        lines.append(
            f"        model_env_global: {'true' if p.get('model_env_global') else 'false'},"
        )
        lines.append(f"        runtime_only: {'true' if p.get('runtime_only') else 'false'},")
        lines.append("    },")
    lines.extend(
        [
            "];",
            "",
            "/// First non-empty environment variable from `keys`.",
            "#[must_use]",
            "pub fn first_nonempty_env(keys: &[&str]) -> Option<String> {",
            "    for key in keys {",
            "        if let Ok(value) = std::env::var(key)",
            "            && !value.trim().is_empty()",
            "        {",
            "            return Some(value);",
            "        }",
            "    }",
            "    None",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def gen_keyring(providers: list[dict], keyring_only: list[dict]) -> str:
    lines = list(HEADER)
    lines.extend(
        [
            "use crate::KeyringSlotDef;",
            "",
            "/// Canonical keyring slots mirrored into the sidecar process environment on spawn.",
            "pub static KEYRING_SLOT_REGISTRY: &[KeyringSlotDef] = &[",
        ]
    )
    seen_slots: set[str] = set()
    for p in providers:
        slot = p["keyring_slot"]
        if slot in seen_slots:
            continue
        seen_slots.add(slot)
        envs = ", ".join(rust_str(e) for e in p["env_api_key"])
        lines.append("    KeyringSlotDef {")
        lines.append(f"        slot: {rust_str(slot)},")
        lines.append(f"        env_candidates: &[{envs}],")
        lines.append("    },")
    for k in keyring_only:
        slot = k["slot"]
        if slot in seen_slots:
            continue
        seen_slots.add(slot)
        envs = ", ".join(rust_str(e) for e in k["env_api_key"])
        lines.append("    KeyringSlotDef {")
        lines.append(f"        slot: {rust_str(slot)},")
        lines.append(f"        env_candidates: &[{envs}],")
        lines.append("    },")
    lines.append("];")
    lines.append("")
    lines.append("/// Map informal slot aliases to the canonical keyring slot id.")
    lines.append("///")
    lines.append("/// `slot` should already be lowercased.")
    lines.append("#[must_use]")
    lines.append("pub fn canonicalize_keyring_slot(slot: &str) -> &str {")
    lines.append("    match slot {")
    seen_alias: set[str] = set()
    for p in providers:
        for a in p.get("keyring_aliases") or []:
            if a in seen_alias:
                continue
            seen_alias.add(a)
            lines.append(f"        {rust_str(a)} => {rust_str(p['keyring_slot'])},")
    lines.append("        other => other,")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_example(providers: list[dict]) -> str:
    lines = [
        "# @generated by scripts/generate-providers.py — fragment for config examples.",
        "# Defaults + env names from crates/shared-defs/providers.toml.",
        "# Rich commentary / popular model lists: crates/config/assets/config.advanced.example.toml",
        "",
    ]
    for p in providers:
        if p.get("runtime_only"):
            continue
        lines.append(f"# [{p['id']}] {p.get('display_name', p['id'])}")
        if p.get("docs_url"):
            lines.append(f"# Docs: {p['docs_url']}")
        env_bits = []
        for e in p.get("env_api_key") or []:
            env_bits.append(e)
        for e in p.get("env_base_url") or []:
            env_bits.append(f"{e} (optional)")
        for e in p.get("env_model") or []:
            env_bits.append(f"{e} (optional)")
        if env_bits:
            lines.append(f"# Env: {', '.join(env_bits)}")
        lines.append(f"# [providers.{p['toml_field']}]")
        lines.append(f'# api_key = "YOUR_{p["rust_variant"].upper()}_KEY"')
        lines.append(f'# base_url = {rust_str(p["default_base_url"])}')
        lines.append(f'# model = {rust_str(p["default_model"])}')
        lines.append("")
    return "\n".join(lines)


def write(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"OK: {path.relative_to(ROOT)}")


def main() -> None:
    data = tomllib.loads(SRC.read_text(encoding="utf-8"))
    providers = data["provider"]
    keyring_only = data.get("keyring_only") or []
    facade = [p for p in providers if not p.get("runtime_only")]

    env_rs = gen_provider_env(providers)
    write(OUT_DEFAULTS_CONFIG, gen_defaults(facade))
    write(OUT_DEFAULTS_RUNTIME, gen_defaults(providers))
    write(OUT_KIND, gen_provider_kind(facade))
    write(OUT_API, gen_api_provider(providers))
    write(OUT_PROVIDERS_TOML, gen_providers_toml(facade))
    write(OUT_PROVIDERS_CFG, gen_providers_config(providers))
    write(OUT_ENV_CONFIG, env_rs)
    write(OUT_ENV_RUNTIME, env_rs)
    write(OUT_KEYRING, gen_keyring(providers, keyring_only))
    write(OUT_EXAMPLE, gen_example(providers))

    facade_ids = [p["id"] for p in facade]
    write(OUT_DRIFT, "\n".join(facade_ids) + "\n")


if __name__ == "__main__":
    main()
