#!/usr/bin/env python3
"""Helpers for LHT harness headless tests (task TOML, config merge, probe parse)."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover
    import tomli as tomllib  # type: ignore

PROFILE_FILES: dict[str, str] = {
    "harness_off": "lht_off.toml",
    "harness_default": "lht_on.toml",
    "harness_strict": "lht_strict.toml",
    "harness_layer1_only": "lht_layer1_only.toml",
    "lht_off": "lht_off.toml",
    "lht_on": "lht_on.toml",
    "lht_strict": "lht_strict.toml",
    "lht_layer1_only": "lht_layer1_only.toml",
}


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def profiles_dir() -> Path:
    """Harness profile TOMLs (migrated docs/harness/fixtures → fixtures/harness)."""
    root = repo_root()
    for rel in (
        "fixtures/harness/lht-eval-arms",
        "docs/harness/fixtures/lht-eval-arms",
    ):
        path = root / rel
        if path.is_dir():
            return path
    return root / "fixtures/harness/lht-eval-arms"


def resolve_profile_path(profile: str) -> Path:
    name = PROFILE_FILES.get(profile)
    if not name:
        known = ", ".join(sorted(set(PROFILE_FILES.keys())))
        raise SystemExit(f"Unknown harness profile '{profile}'. Known: {known}")
    path = profiles_dir() / name
    if not path.is_file():
        raise SystemExit(f"Profile file not found: {path}")
    return path


def default_base_config_path() -> Path | None:
    home = Path.home()
    for candidate in (
        home / ".zagens" / "config.toml",
        home / ".deepseek" / "config.toml",
    ):
        if candidate.is_file():
            return candidate
    return None


def strip_long_horizon_section(text: str) -> str:
    """Remove [long_horizon] table and nested tables from config text."""
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    skip = False
    for line in lines:
        stripped = line.strip()
        if re.match(r"^\[long_horizon(\.|])", stripped):
            skip = True
            continue
        if skip:
            if stripped.startswith("[") and not stripped.startswith("[long_horizon"):
                skip = False
            else:
                continue
        out.append(line)
    return "".join(out).rstrip() + "\n"


def merge_config(base_path: Path | None, profile_path: Path, out_path: Path) -> None:
    base_text = ""
    if base_path and base_path.is_file():
        base_text = base_path.read_text(encoding="utf-8")
    else:
        base_text = "# generated by lht-harness — no base config found\n"
    profile_text = profile_path.read_text(encoding="utf-8")
    merged = strip_long_horizon_section(base_text)
    if merged and not merged.endswith("\n\n"):
        merged += "\n"
    merged += "\n# --- harness profile overlay ---\n"
    merged += profile_text.strip() + "\n"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(merged, encoding="utf-8")


def config_hash(path: Path) -> str:
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    return f"sha256:{digest[:16]}"


def load_tasks(spec_path: Path, task_id: str | None = None) -> list[dict[str, Any]]:
    raw = tomllib.loads(spec_path.read_text(encoding="utf-8"))
    tasks = raw.get("task") or []
    if not isinstance(tasks, list):
        raise SystemExit(f"Invalid task spec (expected [[task]] entries): {spec_path}")
    if task_id:
        tasks = [t for t in tasks if t.get("id") == task_id]
        if not tasks:
            raise SystemExit(f"Task id not found in {spec_path}: {task_id}")
    return tasks


def parse_probe_summary(lines: list[str]) -> dict[str, Any]:
    summary = {
        "continue_injected": 0,
        "gate_skip_graph_complete": 0,
        "verify_gate_red": 0,
        "unverified_acceptance_nudge": 0,
        "blocked": 0,
        "step_limit": 0,
    }
    events: list[str] = []
    for line in lines:
        if "[lht-probe]" not in line and "long_horizon." not in line:
            continue
        events.append(line.strip())
        if "continue_injected" in line:
            summary["continue_injected"] += 1
        if "gate_skip" in line and "graph_complete" in line:
            summary["gate_skip_graph_complete"] += 1
        if "verify_gate" in line and "verdict=red" in line.lower():
            summary["verify_gate_red"] += 1
        if "unverified_acceptance" in line:
            summary["unverified_acceptance_nudge"] += 1
        if "long_horizon.blocked" in line or " blocked " in line:
            summary["blocked"] += 1
        if "step_limit" in line:
            summary["step_limit"] += 1
    return {"summary": summary, "events": events}


def classify_outcome(
    *,
    oracle_passed: bool | None,
    turn_status: str | None,
    task_graph: dict[str, Any],
    probe_summary: dict[str, int],
    harness_ok: bool,
    infra: bool,
    timed_out: bool,
) -> str:
    if infra:
        return "infra"
    if timed_out:
        return "timeout"
    if not harness_ok:
        return "harness_misconfig"
    incomplete = bool(task_graph.get("incomplete"))
    open_items = int(task_graph.get("open_items") or 0)
    completion_pct = int(task_graph.get("completion_pct") or 0)
    if oracle_passed is True:
        return "ok"
    if oracle_passed is False:
        if not incomplete and open_items == 0 and completion_pct >= 100:
            return "false_green"
        if probe_summary.get("gate_skip_graph_complete", 0) > 0 and open_items == 0:
            return "harness_regression"
        if turn_status == "completed" and open_items > 0:
            return "harness_regression"
        return "task_failed"
    return "infra"


def cmd_merge_config(args: argparse.Namespace) -> int:
    base = Path(args.base) if args.base else default_base_config_path()
    profile = resolve_profile_path(args.profile)
    out = Path(args.out)
    merge_config(base, profile, out)
    print(str(out))
    return 0


def cmd_load_tasks(args: argparse.Namespace) -> int:
    spec = Path(args.spec)
    tasks = load_tasks(spec, args.task_id or None)
    print(json.dumps(tasks, ensure_ascii=False, indent=2))
    return 0


def cmd_parse_probe(args: argparse.Namespace) -> int:
    text = Path(args.file).read_text(encoding="utf-8", errors="replace")
    parsed = parse_probe_summary(text.splitlines())
    print(json.dumps(parsed, ensure_ascii=False, indent=2))
    return 0


def cmd_classify_outcome(args: argparse.Namespace) -> int:
    payload = json.loads(Path(args.input).read_text(encoding="utf-8"))
    outcome = classify_outcome(
        oracle_passed=payload.get("oracle_passed"),
        turn_status=payload.get("turn_status"),
        task_graph=payload.get("task_graph") or {},
        probe_summary=payload.get("probe_summary") or {},
        harness_ok=bool(payload.get("harness_ok")),
        infra=bool(payload.get("infra")),
        timed_out=bool(payload.get("timed_out")),
    )
    print(outcome)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="LHT harness test utilities")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_merge = sub.add_parser("merge-config")
    p_merge.add_argument("--profile", required=True)
    p_merge.add_argument("--out", required=True)
    p_merge.add_argument("--base", default="")
    p_merge.set_defaults(func=cmd_merge_config)

    p_tasks = sub.add_parser("load-tasks")
    p_tasks.add_argument("--spec", required=True)
    p_tasks.add_argument("--task-id", default="")
    p_tasks.set_defaults(func=cmd_load_tasks)

    p_probe = sub.add_parser("parse-probe")
    p_probe.add_argument("--file", required=True)
    p_probe.set_defaults(func=cmd_parse_probe)

    p_out = sub.add_parser("classify-outcome")
    p_out.add_argument("--input", required=True, help="JSON file with classification inputs")
    p_out.set_defaults(func=cmd_classify_outcome)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
